### ISSUE TITLE
gitolite.pub rather than id_rsa.pub not working as admin key

### ISSUE THREAD

**Issue by drnic** [drnic/gitlabhq-boshrelease#1]
When I set the initial_admin_key to my ~/.ssh/gitolite.pub, I am asked for a password instead of it working as expected. When I return to my id_rsa.pub then it works.

``` yaml
properties:
  git:
    login: git
    initial_admin_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDTUdTt0T9j6UxN6izjITtYytbQNfmRrkD4xf4yEPyewFGXrSPkcgmTrJmQAEYSM6cqYwnNrTZHtILagi0Ww5wPDU06PaRvSOQmggUfHCU8az2yZ+ouDe25vuIfEe9z2x9tVwBQ/j4CI5lBLpANJl2HtEVghHU/x9vWcJXYgedezVFxIlZcXKl92T5VcOcuCRgjtcoDBW74nQ/JmalGH6ZDRd4yg2+aE8e08Q2ZO9pYCIsyCuAbokQgOv188OhgFuS3QypyuElU36s+q5toFQ/+8v5EiJGOxmFPAHjkDIh1hcZl6GwTFGgqlHG4w33E9ke3ZIYz6jhlqLWQyZTL5NrT drnic@drnic
```
